<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFrameworks>net10.0</TargetFrameworks>
	<OutputType>Library</OutputType>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<PackageId>RJohnsonPGH.Tftp.Net</PackageId>
	<PackageLicenseExpression>MS-PL</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/RJohnsonPGH/tftp.net</PackageProjectUrl>
	<PackageTags>TFTP library</PackageTags>
	<VersionSuffix></VersionSuffix>
	<Authors>RJohnsonPGH</Authors>
	<PackageReleaseNotes>Initial release</PackageReleaseNotes>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
	  <InternalsVisibleTo Include="Tftp.Net.Tests" />
	<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
	<PackageReference Include="Polly" Version="8.7.0" />
  </ItemGroup>
</Project>